spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashopclone
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: none
=======
      ddl-auto: update
>>>>>>> 8cfa53b7af178cf045c536dc0da5fcfb5feb30cb
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace